<a href="https://colab.research.google.com/github/np03cs4s240229-blip/Concepts-and-Technologies-of-AI/blob/main/Worksheet1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

arr_empty = np.empty((2, 2))
print(arr_empty)


[[2.68557302e-315 0.00000000e+000]
 [6.67490449e-310 6.67495147e-310]]


In [ ]:
import numpy as np

arr_one = np.ones((4,2))
print(arr_one)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
import numpy as np

arr_full = np.full((3, 3), 7)
print(arr_full)


[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
arr_zeros_like = np.zeros_like(a)
print(arr_zeros_like)


[[0 0 0]
 [0 0 0]]


In [ ]:
import numpy as np

arr_ones_like = np.ones_like(a)
print(arr_ones_like)


[[1 1 1]
 [1 1 1]]


In [ ]:
import numpy as np

new_list = [1, 2, 3, 4]
arr_from_list = np.array(new_list)
print(arr_from_list)


[1 2 3 4]


In [ ]:
import numpy as np

arr_range = np.arange(10, 50)
print(arr_range)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
import numpy as np

arr_mat = np.arange(9).reshape(3, 3)
print(arr_mat)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
import numpy as np

identity_mat = np.eye(3)
print(identity_mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np

rand_arr = np.random.random(30)
mean_value = rand_arr.mean()

print(rand_arr)
print("Mean:", mean_value)


[0.53933159 0.18603186 0.21869482 0.77180785 0.79399523 0.97679391
 0.43537065 0.42285749 0.16413078 0.45347883 0.40874094 0.46094952
 0.45089895 0.73409387 0.66442732 0.54777998 0.97675999 0.38936644
 0.30055148 0.3960029  0.63670594 0.70848507 0.91124019 0.10781072
 0.32852673 0.59889522 0.26716305 0.46730517 0.8238217  0.4486844 ]
Mean: 0.5196900858555507


In [ ]:
import numpy as np

rand_10x10 = np.random.random((10, 10))
min_val = rand_10x10.min()
max_val = rand_10x10.max()

print("Min:", min_val)
print("Max:", max_val)


Min: 0.02106259815229461
Max: 0.9997583215264115


In [ ]:
import numpy as np

arr_zero = np.zeros(10)
arr_zero[4] = 1
print(arr_zero)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
import numpy as np

arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print(reversed_arr)


[0 4 0 0 2 1]


In [ ]:
import numpy as np

border_arr = np.ones((5, 5))
border_arr[1:-1, 1:-1] = 0
print(border_arr)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
import numpy as np

checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v= np.array([9,10])
w= ([11,12])

#1. Add the two array
add_xy = x + y
print(add_xy)

#2 subtract the two array
sub_xy = x - y
print(sub_xy)

#3 multiply the array with any integer
mul_x = 3 * x
print(mul_x)

#4 square of each element of the array
square_x = x**2
print(square_x)

#5 dot product
#v(and)w
dot_vw = np.dot(v, w)
print(dot_vw)

#x(and)v
dot_xv = np.dot(x, v)
print(dot_xv)

#x(and)y
dot_xy = np.dot(x, y)
print(dot_xy)


#6 concatenate
#x(and)y
concanate_xy = np.concatenate((x, y), axis=0)
print(concanate_xy)

#v(and)w
vw_col = np.column_stack((v, w))
print(vw_col)

#7 concatenate[x(and)v]
np.column_stack((x, v))







[[ 6  8]
 [10 13]]
[[-4 -4]
 [-4 -3]]
[[ 3  6]
 [ 9 15]]
[[ 1  4]
 [ 9 25]]
219
[29 77]
[[19 22]
 [50 58]]
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 11]
 [10 12]]


array([[ 1,  2,  9],
       [ 3,  5, 10]])

In [ ]:
import numpy as np

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

A_inv = np.linalg.inv(A)
result1 = A @ A_inv

print("A * A^-1 =\n", result1)



AB = A @ B
BA = B @ A

print("AB =\n", AB)
print("BA =\n", BA)
print("Are AB and BA equal? →", np.array_equal(AB, BA))



left_side = (AB).T
right_side = B.T @ A.T

print("(AB)^T =\n", left_side)
print("B^T * A^T =\n", right_side)
print("Are they equal? →", np.array_equal(left_side, right_side))



A * A^-1 =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]
Are AB and BA equal? → False
(AB)^T =
 [[23 51]
 [13 29]]
B^T * A^T =
 [[23 51]
 [13 29]]
Are they equal? → True


In [ ]:
import numpy as np

A = np.array([[ 2, -3,  1],
              [ 1, -1,  2],
              [ 3,  1, -1]])

B = np.array([-1, -3, 9])

A_inv = np.linalg.inv(A)
X = A_inv @ B
print("Solution using inverse:", X)

X2 = np.linalg.solve(A, B)
print("Solution using np.linalg.solve:", X2)


Solution using inverse: [ 2.  1. -2.]
Solution using np.linalg.solve: [ 2.  1. -2.]


In [ ]:
import time
import numpy as np

# 1. ELEMENT-WISE ADDITION

# Python List addition
list1 = [i for i in range(1_000_000)]
list2 = [i for i in range(1_000_000)]

start = time.time()
list_add = [list1[i] + list2[i] for i in range(1_000_000)]
end = time.time()

print("Python List Addition Time:", end - start, "seconds")

# NumPy addition
arr1 = np.arange(1_000_000)
arr2 = np.arange(1_000_000)

start = time.time()
np_add = arr1 + arr2
end = time.time()

print("NumPy Array Addition Time:", end - start, "seconds")

# 2. ELEMENT-WISE MULTIPLICATION

# Python List multiplication
start = time.time()
list_mul = [list1[i] * list2[i] for i in range(1_000_000)]
end = time.time()

print("\nPython List Multiplication Time:", end - start, "seconds")

# NumPy multiplication
start = time.time()
np_mul = arr1 * arr2
end = time.time()

print("NumPy Array Multiplication Time:", end - start, "seconds")


# 3. DOT PRODUCT

# Python List Dot Product
start = time.time()
dot_list = sum(list1[i] * list2[i] for i in range(1_000_000))
end = time.time()

print("\nPython List Dot Product Time:", end - start, "seconds")

# NumPy Dot Product
start = time.time()
dot_np = np.dot(arr1, arr2)
end = time.time()

print("NumPy Array Dot Product Time:", end - start, "seconds")


# 4. MATRIX MULTIPLICATION (1000 x 1000)

# Python list matrix multiplication
matrix1 = [[1] * 1000 for _ in range(1000)]
matrix2 = [[1] * 1000 for _ in range(1000)]

start = time.time()
result_matrix = [[sum(a * b for a, b in zip(row, col))
                  for col in zip(*matrix2)]
                  for row in matrix1]
end = time.time()

print("\nPython List Matrix Multiplication Time:", end - start, "seconds")


# NumPy matrix multiplication
np_matrix1 = np.ones((1000, 1000))
np_matrix2 = np.ones((1000, 1000))

start = time.time()
np_result = np_matrix1 @ np_matrix2   # or np.dot()
end = time.time()

print("NumPy Array Matrix Multiplication Time:", end - start, "seconds")


Python List Addition Time: 0.11660528182983398 seconds
NumPy Array Addition Time: 0.004676103591918945 seconds

Python List Multiplication Time: 0.12682771682739258 seconds
NumPy Array Multiplication Time: 0.00580906867980957 seconds

Python List Dot Product Time: 0.10778427124023438 seconds
NumPy Array Dot Product Time: 0.001875162124633789 seconds

Python List Matrix Multiplication Time: 81.21696519851685 seconds
NumPy Array Matrix Multiplication Time: 0.07106924057006836 seconds
